import FAQ from "@/components/FAQ";
import { FAQDataSchema, fetchFAQdata } from "@/data/dataFetchUtil";
import { Container, Typography } from "@mui/material";
import { GetStaticProps, InferGetServerSidePropsType } from "next";
import Head from "next/head";

const Home = ({ faq }: InferGetServerSidePropsType<typeof getStaticProps>) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Frontend Mentor | FAQ Accordion Card</title>
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <Container component={"main"} disableGutters>
        <FAQ faqList={faq} />
      </Container>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<{ faq: FAQDataSchema }> = async (
  context
) => {
  const faq = await fetchFAQdata();
  return {
    props: {
      faq,
    },
  };
};
