import Head from "next/head";
import Image from "next/image";
import { League_Spartan } from "next/font/google";
import ReviewCard from "@/components/ReviewCard";
import { Container } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Frontend Mentor | Social proof section</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container component={"main"} id="main" disableGutters>
        <ReviewCard
          name="Colton Smith"
          src="/images/image-colton.jpg"
          content="We needed the same printed design as the one we had ordered a week prior.
          Not only did they find the original order, but we also received it in time.
          Excellent!"
          positionHorizontal={{
            start: 1,
            end: 4,
          }}
          alignment="start"
        />
        <ReviewCard
          name="Irene Roberts"
          src="/images/image-irene.jpg"
          content="Customer service is always excellent and very quick turn around. Completely
          delighted with the simplicity of the purchase and the speed of delivery."
          positionHorizontal={{
            start: 3,
            end: 6,
          }}
          alignment="center"
        />
        <ReviewCard
          name="Anne Wallace"
          src="/images/image-anne.jpg"
          content="Put an order with this company and can only praise them for the very high
          standard. Will definitely use them again and recommend them to everyone!"
          positionHorizontal={{
            start: 5,
            end: 8,
          }}
          alignment="end"
        />
        <Image
          src={"/images/bg-pattern-top-desktop.svg"}
          fill
          id="bg-top"
          alt="bg-top"
          style={{
            position: "absolute",
            top: 0,
            left: "-70vw",
          }}
        />
        <Image
          src={"/images/bg-pattern-bottom-desktop.svg"}
          fill
          id="bg-bottom"
          alt="bg-bottom"
          style={{
            position: "absolute",
            bottom: 0,
            left: "28vw",
          }}
        />
      </Container>
    </>
  );
}
